packages:
  # Dependencies
  rust-atoi:
    # Needed by: sqlx-*
    # https://bugzilla.redhat.com/show_bug.cgi?id=2268045
    paths: [ rust-atoi ]
    specfile_path: rust-atoi.spec
    upstream_package_name: atoi
    downstream_package_name: rust-atoi
    # Don't run rust2rpm because there is already a package review
    actions: &Actions-Package-no-rust2rpm
      fix-spec-file: []
      create-archive:
        - sh -c 'spectool -g -s0 ${PACKIT_DOWNSTREAM_PACKAGE_NAME}.spec'
        - sh -c 'echo ${PACKIT_UPSTREAM_PACKAGE_NAME}-${PACKIT_PROJECT_VERSION}.crate'
      get-current-version:
        - sh -c 'rpmspec -q --qf "%{Version}" --srpm ${PACKIT_DOWNSTREAM_PACKAGE_NAME}.spec'

  # Actual sqlx packages
  rust-sqlx:
    # https://github.com/launchbadge/sqlx
    paths: [ rust-sqlx ]
    specfile_path: rust-sqlx.spec
    upstream_package_name: sqlx
    downstream_package_name: rust-sqlx
    actions: &Actions-Package-rust2rpm
      <<: *Actions-Package-no-rust2rpm
      fix-spec-file:
        - sh -c 'rust2rpm ${PACKIT_UPSTREAM_PACKAGE_NAME}'
  rust-sqlx-macros:
    # https://github.com/launchbadge/sqlx
    paths: [ rust-sqlx-macros ]
    specfile_path: rust-sqlx-macros.spec
    upstream_package_name: sqlx-macros
    downstream_package_name: rust-sqlx-macros
    actions: &Actions-Package-fix-sqlx-license
      <<: *Actions-Package-rust2rpm
      fix-spec-file:
        - sh -c 'rust2rpm -I ${PACKIT_UPSTREAM_PACKAGE_NAME}'
        - "sh -c 'sed -i \"s/# FIXME: no license files detected/cat license_files.txt/e\" ${PACKIT_DOWNSTREAM_PACKAGE_NAME}.spec'"
  rust-sqlx-mysql:
    # https://github.com/launchbadge/sqlx
    paths: [ rust-sqlx-mysql ]
    specfile_path: rust-sqlx-mysql.spec
    upstream_package_name: sqlx-mysql
    downstream_package_name: rust-sqlx-mysql
    actions: *Actions-Package-no-rust2rpm
  rust-sqlx-postgres:
    # https://github.com/launchbadge/sqlx
    paths: [ rust-sqlx-postgres ]
    specfile_path: rust-sqlx-postgres.spec
    upstream_package_name: sqlx-postgres
    downstream_package_name: rust-sqlx-postgres
    actions: *Actions-Package-no-rust2rpm
  rust-sqlx-sqlite:
    # https://github.com/launchbadge/sqlx
    paths: [ rust-sqlx-sqlite ]
    specfile_path: rust-sqlx-sqlite.spec
    upstream_package_name: sqlx-sqlite
    downstream_package_name: rust-sqlx-sqlite
    # Requires rust2rpm -p 
    actions: *Actions-Package-no-rust2rpm
  rust-sqlx-macros-core:
    # https://github.com/launchbadge/sqlx
    paths: [ rust-sqlx-macros-core ]
    specfile_path: rust-sqlx-macros-core.spec
    upstream_package_name: sqlx-macros-core
    downstream_package_name: rust-sqlx-macros-core
    actions: *Actions-Package-fix-sqlx-license
  rust-sqlx-core:
    # https://github.com/launchbadge/sqlx
    paths: [ rust-sqlx-core ]
    specfile_path: rust-sqlx-core.spec
    upstream_package_name: sqlx-core
    downstream_package_name: rust-sqlx-core
    actions: *Actions-Package-fix-sqlx-license

srpm_build_deps:
  - rust2rpm

jobs:
  - job: copr_build
    trigger: commit
    update_release: false
    targets:
      - fedora-rawhide
