# Generated by rust2rpm 26
%bcond_without check
%global debug_package %{nil}

%global crate finl_unicode

Name:           rust-finl_unicode
Version:        1.2.0
Release:        %autorelease
Summary:        Library for handling Unicode functionality for finl

License:        MIT OR Apache-2.0
URL:            https://crates.io/crates/finl_unicode
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24
# Do downstream crate metadata changes programmatically in %%prep. Since %%prep
# runs before %%generate_buildrequires, we must add the following manually
# rather than generating a dynamic BuildRequires via rust2rpm.toml.
BuildRequires:  tomcli

%global _description %{expand:
Library for handling Unicode functionality for finl (categories and
grapheme segmentation).}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE-APACHE
%license %{crate_instdir}/LICENSE-MIT
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+categories-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+categories-devel %{_description}

This package contains library source intended for building other packages which
use the "categories" feature of the "%{crate}" crate.

%files       -n %{name}+categories-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+grapheme_clusters-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+grapheme_clusters-devel %{_description}

This package contains library source intended for building other packages which
use the "grapheme_clusters" feature of the "%{crate}" crate.

%files       -n %{name}+grapheme_clusters-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep
# Do not depend on criterion; it is needed only for benchmarks.
tomcli set Cargo.toml del dev-dependencies.criterion

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
