[features]
enable-all = true

[[package.extra-sources]]
number = 10
file = "https://github.com/launchbadge/sqlx/raw/v%{version}/LICENSE-APACHE"
comments = [
    "Fix missing LICENSE-* files in released crates",
    "https://github.com/launchbadge/sqlx/issues/3237",
]
[[package.extra-sources]]
number = 11
file = "https://github.com/launchbadge/sqlx/raw/v%{version}/LICENSE-MIT"
comments = [
    "Fix missing LICENSE-* files in released crates",
    "https://github.com/launchbadge/sqlx/issues/3237",
]

[scripts.prep]
pre = ["cp -p '%{SOURCE10}' '%{SOURCE11}' ."]

[package]
cargo-toml-patch-comments = [
    "- Bump libsqlite3 dependency",
    "  https://github.com/launchbadge/sqlx/pull/3148",
    "- Fix libsqlite3 features",
    "- Fix missing chrono.clock feature",
    "  https://github.com/launchbadge/sqlx/issues/3332",
]

[[package.extra-patches]]
comments = [
    "https://github.com/launchbadge/sqlx/pull/3281",
    "Add SQLITE_OPEN_URI to all in-memory sqlite",
]
file = "sqlx-sqlite-0.7.4-Fix_openuri_flag.patch"
number = 10

[tests]
comments = [
    "resolve dependency loop with sqlx",
]
run = ["none"]
