[[package.extra-sources]]
number = 10
file = "https://github.com/launchbadge/sqlx/raw/v%{version}/LICENSE-APACHE"
comments = [
    "Fix missing LICENSE-* files in released crates",
    "https://github.com/launchbadge/sqlx/issues/3237",
]
[[package.extra-sources]]
number = 11
file = "https://github.com/launchbadge/sqlx/raw/v%{version}/LICENSE-MIT"
comments = [
    "Fix missing LICENSE-* files in released crates",
    "https://github.com/launchbadge/sqlx/issues/3237",
]

[scripts.prep]
pre = ["cp -p '%{SOURCE10}' '%{SOURCE11}' ."]

[package]
extra-files = [
    "%license %{crate_instdir}/LICENSE-APACHE",
    "%license %{crate_instdir}/LICENSE-MIT",
]

[[package.extra-patches]]
comments = [
    "https://github.com/launchbadge/sqlx/pull/3148",
    "Also fix libsqlite3 features",
]
file = "sqlx-sqlite-0.7.4-Fix_libsqlite3-sys.patch"
number = 10

[tests]
comments = [
    "resolve dependency loop with sqlx",
]
run = ["none"]
