[[package.extra-patches]]
comments = [
    "https://github.com/launchbadge/sqlx/pull/3148",
    "Also fix libsqlite3 features",
]
file = "sqlx-sqlite-0.7.4-Fix_libsqlite3-sys.patch"
number = 10

[tests]
comments = [
    "resolve dependency loop with sqlx",
]
run = ["none"]
