# Generated by rust2rpm 26
%bcond_without check
%global debug_package %{nil}

%global crate sqlx-macros-core

Name:           rust-sqlx-macros-core
Version:        0.7.4
Release:        %autorelease
Summary:        Macro support core for SQLx, the Rust SQL toolkit

License:        MIT OR Apache-2.0
URL:            https://crates.io/crates/sqlx-macros-core
Source:         %{crates_source}
# * Fix missing LICENSE-* files in released crates
# * https://github.com/launchbadge/sqlx/issues/3237
Source10:       https://github.com/launchbadge/sqlx/raw/v%{version}/LICENSE-APACHE
# * Fix missing LICENSE-* files in released crates
# * https://github.com/launchbadge/sqlx/issues/3237
Source11:       https://github.com/launchbadge/sqlx/raw/v%{version}/LICENSE-MIT

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Macro support core for SQLx, the Rust SQL toolkit. Not intended to be
used directly.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE-APACHE
%license %{crate_instdir}/LICENSE-MIT
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+_rt-async-std-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+_rt-async-std-devel %{_description}

This package contains library source intended for building other packages which
use the "_rt-async-std" feature of the "%{crate}" crate.

%files       -n %{name}+_rt-async-std-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+_rt-tokio-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+_rt-tokio-devel %{_description}

This package contains library source intended for building other packages which
use the "_rt-tokio" feature of the "%{crate}" crate.

%files       -n %{name}+_rt-tokio-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+_tls-native-tls-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+_tls-native-tls-devel %{_description}

This package contains library source intended for building other packages which
use the "_tls-native-tls" feature of the "%{crate}" crate.

%files       -n %{name}+_tls-native-tls-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+_tls-rustls-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+_tls-rustls-devel %{_description}

This package contains library source intended for building other packages which
use the "_tls-rustls" feature of the "%{crate}" crate.

%files       -n %{name}+_tls-rustls-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+async-std-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+async-std-devel %{_description}

This package contains library source intended for building other packages which
use the "async-std" feature of the "%{crate}" crate.

%files       -n %{name}+async-std-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+bigdecimal-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+bigdecimal-devel %{_description}

This package contains library source intended for building other packages which
use the "bigdecimal" feature of the "%{crate}" crate.

%files       -n %{name}+bigdecimal-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+bit-vec-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+bit-vec-devel %{_description}

This package contains library source intended for building other packages which
use the "bit-vec" feature of the "%{crate}" crate.

%files       -n %{name}+bit-vec-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+chrono-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+chrono-devel %{_description}

This package contains library source intended for building other packages which
use the "chrono" feature of the "%{crate}" crate.

%files       -n %{name}+chrono-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+ipnetwork-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+ipnetwork-devel %{_description}

This package contains library source intended for building other packages which
use the "ipnetwork" feature of the "%{crate}" crate.

%files       -n %{name}+ipnetwork-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+json-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+json-devel %{_description}

This package contains library source intended for building other packages which
use the "json" feature of the "%{crate}" crate.

%files       -n %{name}+json-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+mac_address-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+mac_address-devel %{_description}

This package contains library source intended for building other packages which
use the "mac_address" feature of the "%{crate}" crate.

%files       -n %{name}+mac_address-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+migrate-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+migrate-devel %{_description}

This package contains library source intended for building other packages which
use the "migrate" feature of the "%{crate}" crate.

%files       -n %{name}+migrate-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+mysql-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+mysql-devel %{_description}

This package contains library source intended for building other packages which
use the "mysql" feature of the "%{crate}" crate.

%files       -n %{name}+mysql-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+postgres-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+postgres-devel %{_description}

This package contains library source intended for building other packages which
use the "postgres" feature of the "%{crate}" crate.

%files       -n %{name}+postgres-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+rust_decimal-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+rust_decimal-devel %{_description}

This package contains library source intended for building other packages which
use the "rust_decimal" feature of the "%{crate}" crate.

%files       -n %{name}+rust_decimal-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+sqlite-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+sqlite-devel %{_description}

This package contains library source intended for building other packages which
use the "sqlite" feature of the "%{crate}" crate.

%files       -n %{name}+sqlite-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+sqlx-mysql-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+sqlx-mysql-devel %{_description}

This package contains library source intended for building other packages which
use the "sqlx-mysql" feature of the "%{crate}" crate.

%files       -n %{name}+sqlx-mysql-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+sqlx-postgres-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+sqlx-postgres-devel %{_description}

This package contains library source intended for building other packages which
use the "sqlx-postgres" feature of the "%{crate}" crate.

%files       -n %{name}+sqlx-postgres-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+sqlx-sqlite-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+sqlx-sqlite-devel %{_description}

This package contains library source intended for building other packages which
use the "sqlx-sqlite" feature of the "%{crate}" crate.

%files       -n %{name}+sqlx-sqlite-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+time-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+time-devel %{_description}

This package contains library source intended for building other packages which
use the "time" feature of the "%{crate}" crate.

%files       -n %{name}+time-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+tokio-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tokio-devel %{_description}

This package contains library source intended for building other packages which
use the "tokio" feature of the "%{crate}" crate.

%files       -n %{name}+tokio-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+uuid-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+uuid-devel %{_description}

This package contains library source intended for building other packages which
use the "uuid" feature of the "%{crate}" crate.

%files       -n %{name}+uuid-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
cp -p '%{SOURCE10}' '%{SOURCE11}' .
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires -a

%build
%cargo_build -a

%install
%cargo_install -a

%if %{with check}
%check
%cargo_test -a
%endif

%changelog
%autochangelog
